theme: jekyll-theme-cayman
title: DevOpsSustain 2026
description: DevOpsSustain 2026 | Second International Workshop on DevOps for Sustainability, co-located with FSE 2026
github:
  is_project_page: false
